---
- hosts: local
  tasks:
    - name: Install nano
      apt: pkg=nano state=removed update_cache=true
    - name: Create directory for php5-fpm logs
      file: path=/var/log/php5-fpm state=directory owner=root group=root mode=0700
    - name: Create Admin User
      user:
        name=admin
        password=admin123
        groups=sudo
        append=yes
        shell=/bin/bash


# Ejemplo para instalar y configurar algo (No podemos indagar más porque no sabemos python 
# y no entendemos como se harían otras cosas como modificar parametros y otras configuraciones)
#  tasks:
#    - name: Install algo
#      apt: pkg=algo state=installed update_cache=true
#  handlers:
#    - name: restart algo
#      action: service name=algo state=restarted
